title: Mike Peiman | Better
markdown: kramdown
highlighter: pygments # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]
description: "A blog on self-improvement, overcoming challenges, 
achieving lasting fulfillment and success, and making the world a better place."
twitter_username: 
github_username:
permalink: none
comments: false

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Mike Peiman"
